### ISSUE TITLE
Нужно было указать, наверное, что это перевод ангоязычной статьи

### ISSUE THREAD

**Issue by wantToHawaii** [Sigizmund2012/gulp-bower-sass-jquery-and-bootstrap-Wordpress-template#1]
Мне кажется что это оригинал, не так ли?
https://github.com/synapticism/wordpress-gulp-starter-kit

**Comment by Sigizmund2012** [comment]
В описании указана ссылка на оригинал. Я много чего изменил в нём, по сути это уже не стартовый набор, а сборка для генерации и технической поддержки конкретно шаблона для моего сайта. В паблик выставил, что бы восстановить тему, если локальные файлы потеряю, ну и вообще, вдруг пригодится кому.
